### ISSUE TITLE
Document + example how to implement a custom login

### ISSUE THREAD

**Issue by almarklein** [almarklein/timetagger#145]
For self-hosters.

**Comment by boehs** [comment]
I have done on my fork: boehs/timetagger

**Comment by almarklein** [comment]
@boehs I don't see where. Was it on a branch that has been deleted or something?

**Comment by boehs** [comment]
> @boehs I don't see where. Was it on a branch that has been deleted or something?

Where did it go!? I'm so confused, I deployed it to my server by git cloning.... In any case, it should be there now

**Comment by sergeolkhovik** [comment]
Gentlemen, I want to run an instance of TT under nginx + docker environment and have some auth for only me. Let me share this info, hope it will be useful.
So I did this in nginx.conf:
```
    location /timetagger {
        proxy_pass http://timetagger:80;
    }
    location /timetagger/login {
        auth_basic "Timetagger";
        auth_basic_user_file /etc/nginx/conf.d/auth;
        proxy_pass http://timetagger:80;
    }
```
Auth file is created with a htpasswd tool and contains only one user.
And here's my docker-compose conf:
```
  timetagger:
    container_name: timetagger
    build:
      context: timetagger
      dockerfile: Dockerfile
    environment:
      - TIMETAGGER_DATADIR=/root/timedata
    volumes:
      - ./conf/timetagger:/root
      - ./timetagger/timetagger:/root/timetagger
    ports:
      - 8081:80
    networks:
      - backend
```

Next, I copied run.py from timetagger cloned repo into conf/timetagger and did these modifications:
```
% diff -u conf/timetagger/run.py timetagger/run.py
--- conf/timetagger/run.py      2022-02-22 12:34:53.927671913 +0200
+++ timetagger/run.py   2022-02-21 12:31:29.114317818 +0200
@@ -20,10 +20,6 @@
 )


-AUTH_KEY='authorization'
-AUTH_PW='Basic xxxx'
-AUTH_USER='xxxx'
-
 logger = logging.getLogger("asgineer")

 # Get sets of assets provided by TimeTagger
@@ -103,13 +99,11 @@
     """

     # Establish that we can trust the client
-    #return 403, {}, repr(request.headers)
-    #if not (request.host in ("localhost", "127.0.0.1")):
-    if not (request.host in ("localhost", "127.0.0.1") or AUTH_KEY in request.headers and request.headers[AUTH_KEY] == AUTH_PW):
+    if request.host not in ("localhost", "127.0.0.1"):
         return 403, {}, "forbidden: must be on localhost"

     # Return the webtoken for the default user
-    token = await get_webtoken_unsafe(AUTH_USER)
+    token = await get_webtoken_unsafe("defaultuser")
     return 200, {}, dict(token=token)
```

So nginx passes authorization header that will contain 'Basic xxxx', and that value may be parsed (this is base64-value that has user:password text), but I just saved that entire header value and check it on request.
I didn't check cli version yet, but I hope all will be fine, I see API token generated.
