### ISSUE TITLE
Put a Docker image on Dockerhub that skips auth

### ISSUE THREAD

**Issue by almarklein** [almarklein/timetagger#146]
People who self-host might provide other means of authentication and just want a docker container with an open port.

**Comment by dorianim** [comment]
Would be really nice to have! Would you accept a pullrequest on this?

**Comment by almarklein** [comment]
Yes!

**Comment by dorianim** [comment]
I personally prefer the github container registry over dockerhub. Would that be fine for you?

**Comment by almarklein** [comment]
I don't have strong opinions on what registry to use.

**Comment by almarklein** [comment]
I think we still need a way to control auth for the docker image.

**Comment by dorianim** [comment]
I'm currently duin that by passing my own run.py as a volume:
```
services:
        timetagger:
                image: ghcr.io/almarklein/timetagger
                ports:
                        - 3004:80
                volumes:
                        - ./_timetagger:/root/_timetagger
                        - ./run.py:/root/run.py
                restart: always

```
