### ISSUE TITLE
Reverse Proxy authentication trust doesn't work

### ISSUE THREAD

**Issue by cfstras** [almarklein/timetagger#344]
I've come across two issues when looking at reverse proxy authentication:

1. https://github.com/encode/uvicorn/issues/1068 -- This is only an issue when f.ex. testing with localhost. As a workaround, one can use the LAN IP to access the proxy instead.

More importantly:
2. The application server used, uvicorn, has its own logic for parsing the "X-Forwarded-For" header. Combined with the functionality in timetagger, this will mangle/break the list of forwarded IPs for incoming requests, potentially even trusting fake headers sent by a client!
To fix this, one has to `export FORWARDED_ALLOW_IPS=""` to disable the uvicorn parsing.
See [docs](https://www.uvicorn.org/settings/#http)

**Comment by almarklein** [comment]
Sorry for responding so late, this slipped my attention. I haven't looked looked into proxy authentication that much, to be honest. Are there things in TimeTagger that we can do to resolve these issues? PR's welcome :)

Also cc @Rynoxx @mtn-mathi @foorschtbar

**Comment by cfstras** [comment]
My first instinct would be to remove the X-Forwarded-For code from timetagger, trust the functionality in uvicorn and configure it automatically and/or document how to. Though I‘m not sure why it was added in the first place if uvicorn was always used, or, in which usecases it was tested, so we can make sure not to break these.

**Comment by foorschtbar** [comment]
> Sorry for responding so late, this slipped my attention. I haven't looked looked into proxy authentication that much, to be honest. Are there things in TimeTagger that we can do to resolve these issues? PR's welcome :)
> 
> Also cc @Rynoxx @mtn-mathi @foorschtbar

For me, the current solution works at the moment.

**Comment by cfstras** [comment]
Could you please describe the setup you’re using, the flags and env vars, and which headers are passed by your reverse proxy?
In my tests, using oauth2-proxy, timetagger (without the described workaround) would always ignore the `X-Forwarded-User` header.
Upon debugging, I found that uvicorn already parses the X-Forwarded-For, and clears it, and then timetagger tries to check it again and decides to skip proxy auth handling because it‘s missing.

**Comment by Rynoxx** [comment]
@cfstras This config works for me in kuberenetes behind Authentik as the proxy-auth provider.
I'm not seeing any differences in behavior between having `FORWARDED_ALLOW_IPS=""` or not, also tried `*`.

But this might also be because authentik is using a custom header (X-authentik-username) for it and not a X-Forwarded-* header?

```
          env:
            - name: TIMETAGGER_BIND
              value: "0.0.0.0:80"
            - name: TIMETAGGER_CREDENTIALS
              value: "<redacted>"
            - name: TIMETAGGER_LOG_LEVEL
              value: "info"
            - name: TIMETAGGER_DATADIR
              value: "/root/_timetagger"
            - name: TIMETAGGER_PROXY_AUTH_ENABLED
              value: "True"
            - name: TIMETAGGER_PROXY_AUTH_HEADER
              value: "X-authentik-username"
            - name: TIMETAGGER_PROXY_AUTH_TRUSTED
              value: "10.0.0.1/8"
            - name: TZ
              value: "Europe/Stockholm"
```
