### ISSUE TITLE
404 - "only serving at /timetagger/"

### ISSUE THREAD

**Issue by accforgithubtest** [almarklein/timetagger#414]
I have set up a docker compose based set up to try out / test timetagger and get a feel of it.
I have set up TIMETAGGER_CREDENTIALS and able to login and see the test data in the UI at https://timetagger.local.host/. Version 23.9.2.

I am now trying to use web api to push some data using http put as mentioned in [the docs](https://timetagger.readthedocs.io/en/latest/webapi/). authtoken is included in the header as part of both get and put requests.

However both GET (https://timetagger.local.host/api/v2/settings) and PUT (https://timetagger.local.host/api/v2/records) are erroring out with - 
```404 - "only serving at /timetagger/"```

Can you pls suggest what could be causing this issue ? Any suggestions on what I can do to debug ?

My docker compose is -
```
services:
  timetagger:
    image: ghcr.io/almarklein/timetagger:latest
    container_name: timetagger
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./timetagger:/root/_timetagger
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
      - TIMETAGGER_CREDENTIALS=...........
    ports:
      - 80
    labels:
      caddy: timetagger.local.host
      caddy.reverse_proxy: {{upstreams 80}}
      caddy.tls: <<self signed certs details here>>
```

For additional context, I have a few other services already working fine with caddy reverse proxy set-up, adding timetagger to an existing setup, ubuntu host os, docker compose based set up.
