### ISSUE TITLE
Current container image does't start

### ISSUE THREAD

**Issue by DreyCon-Raphael** [almarklein/timetagger#454]
When I install a freshly pulled image from TrueCharts stable, the Container hangs at "deploying" state. The only log entry I can get from the starting process is 
`/usr/local/bin/python: No module named timetagger`

This already started a few versions ago, sadly I don't know the version it began with. The version I started searching for external help at discord with (App Version 23.11.4, Chart Version 5.1.3) as well the one from the newer Chart Version (5.2.0) behave the same.

<details>
  <summary>last logged events on TNS web UI</summary>

```2024-03-01 09:16:59
Back-off restarting failed container dc-timer-timetagger in pod dc-timer-timetagger-69db5749f4-69kbw_ix-dc-timer(a50b1c27-11b1-433d-944b-c071fa9e3015)
2024-03-01 09:16:48
Add eth0 [172.16.0.239/16] from ix-net
2024-03-01 09:16:48
Container image "ghcr.io/almarklein/timetagger:v23.11.4@sha256:df703a7d2a155bbaac27ffa01f42323645798a5dbb3ee1eccd6e050e7c501e53" already present on machine
2024-03-01 09:16:48
Created container dc-timer-timetagger
2024-03-01 09:16:48
Started container dc-timer-timetagger
2024-03-01 09:16:47
Scaled up replica set dc-timer-timetagger-69db5749f4 to 1
2024-03-01 09:16:47
Created pod: dc-timer-timetagger-69db5749f4-69kbw
2024-03-01 09:16:47
Successfully assigned ix-dc-timer/dc-timer-timetagger-69db5749f4-69kbw to ix-truenas
 ```
</details>

As the container doesn't start, I cannot fetch any further logs from inside.

Some details from cli:
<details>
  <summary>sudo k3s kubectl get pods --all-namespaces</summary>

![image](https://github.com/almarklein/timetagger/assets/3204803/f97c16c1-cff1-42c9-9663-c8e7a1580fc6)
</details>

<details>
  <summary>kubectl describe pod -n ix-dc-timer dc-timer-timetagger-69db5749f4-69kbw</summary>

```yaml
Name:             dc-timer-timetagger-69db5749f4-69kbw
Namespace:        ix-dc-timer
Priority:         0
Service Account:  default
Node:             ix-truenas/10.0.0.100
Start Time:       Fri, 01 Mar 2024 09:16:47 +0100
Labels:           app=timetagger-5.2.0
                  app.kubernetes.io/instance=dc-timer
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=timetagger
                  app.kubernetes.io/version=23.11.4
                  helm-revision=7
                  helm.sh/chart=timetagger-5.2.0
                  pod-template-hash=69db5749f4
                  pod.lifecycle=permanent
                  pod.name=main
                  release=dc-timer
Annotations:      k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "ix-net",
                        "interface": "eth0",
                        "ips": [
                            "172.16.1.0"
                        ],
                        "mac": "7a:f4:9e:0d:8b:97",
                        "default": true,
                        "dns": {},
                        "gateway": [
                            "172.16.0.1"
                        ]
                    }]
                  rollme: aIKES
Status:           Running
IP:               172.16.1.0
IPs:
  IP:           172.16.1.0
Controlled By:  ReplicaSet/dc-timer-timetagger-69db5749f4
Containers:
  dc-timer-timetagger:
    Container ID:   containerd://7d6dcbd41db4ab0b426c9b754f3c5df16bba71a9cf53d8329569767c70c4391a
    Image:          ghcr.io/almarklein/timetagger:v23.11.4@sha256:df703a7d2a155bbaac27ffa01f42323645798a5dbb3ee1eccd6e050e7c501e53
    Image ID:       ghcr.io/almarklein/timetagger@sha256:df703a7d2a155bbaac27ffa01f42323645798a5dbb3ee1eccd6e050e7c501e53
    Port:           10286/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 01 Mar 2024 09:30:50 +0100
      Finished:     Fri, 01 Mar 2024 09:30:50 +0100
    Ready:          False
    Restart Count:  10
    Limits:
      amd.com/gpu:         0
      cpu:                 4
      gpu.intel.com/i915:  0
      memory:              8Gi
      nvidia.com/gpu:      0
    Requests:
      amd.com/gpu:         0
      cpu:                 10m
      gpu.intel.com/i915:  0
      memory:              50Mi
      nvidia.com/gpu:      0
    Liveness:              http-get http://:10286/ delay=10s timeout=5s period=10s #success=1 #failure=5
    Readiness:             http-get http://:10286/ delay=10s timeout=5s period=10s #success=2 #failure=5
    Startup:               tcp-socket :10286 delay=10s timeout=2s period=5s #success=1 #failure=60
    Environment:
      TZ:                      Europe/Berlin
      UMASK:                   0022
      UMASK_SET:               0022
      NVIDIA_VISIBLE_DEVICES:  void
      PUID:                    568
      USER_ID:                 568
      UID:                     568
      PGID:                    568
      GROUP_ID:                568
      GID:                     568
      TIMETAGGER_BIND:         0.0.0.0:10286
      TIMETAGGER_CREDENTIALS:  ********:********
      TIMETAGGER_LOG_LEVEL:    info
      tg_pass:                 ********
      tg_user:                 ********
    Mounts:
      /dev/shm from devshm (rw)
      /root/_timetagger from config (rw)
      /shared from shared (rw)
      /tmp from tmp (rw)
      /var/logs from varlogs (rw)
      /var/run from varrun (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  dc-timer-timetagger-config
    ReadOnly:   false
  devshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  8Gi
  shared:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  8Gi
  varlogs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  8Gi
  varrun:
    Type:                     EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:                   Memory
    SizeLimit:                8Gi
QoS Class:                    Burstable
Node-Selectors:               kubernetes.io/arch=amd64
Tolerations:                  node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Topology Spread Constraints:  kubernetes.io/hostname:ScheduleAnyway when max skew 1 is exceeded for selector app.kubernetes.io/instance=dc-timer,app.kubernetes.io/name=timetagger,pod.name=main
                              truecharts.org/rack:ScheduleAnyway when max skew 1 is exceeded for selector app.kubernetes.io/instance=dc-timer,app.kubernetes.io/name=timetagger,pod.name=main
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       15m                    default-scheduler  Successfully assigned ix-dc-timer/dc-timer-timetagger-69db5749f4-69kbw to ix-truenas
  Normal   AddedInterface  15m                    multus             Add eth0 [172.16.0.239/16] from ix-net
  Normal   Created         14m (x4 over 15m)      kubelet            Created container dc-timer-timetagger
  Normal   Started         14m (x4 over 15m)      kubelet            Started container dc-timer-timetagger
  Normal   Pulled          13m (x5 over 15m)      kubelet            Container image "ghcr.io/almarklein/timetagger:v23.11.4@sha256:df703a7d2a155bbaac27ffa01f42323645798a5dbb3ee1eccd6e050e7c501e53" already present on machine
  Warning  BackOff         10m (x34 over 15m)     kubelet            Back-off restarting failed container dc-timer-timetagger in pod dc-timer-timetagger-69db5749f4-69kbw_ix-dc-timer(a50b1c27-11b1-433d-944b-c071fa9e3015)
  Warning  FailedMount     3m7s                   kubelet            Unable to attach or mount volumes: unmounted volumes=[config], unattached volumes=[tmp varlogs varrun config devshm shared]: timed out waiting for the condition
  Normal   SandboxChanged  2m55s                  kubelet            Pod sandbox changed, it will be killed and re-created.
  Normal   AddedInterface  2m55s                  multus             Add eth0 [172.16.1.0/16] from ix-net
  Normal   Pulled          2m (x3 over 2m55s)     kubelet            Container image "ghcr.io/almarklein/timetagger:v23.11.4@sha256:df703a7d2a155bbaac27ffa01f42323645798a5dbb3ee1eccd6e050e7c501e53" already present on machine
  Normal   Created         119s (x3 over 2m55s)   kubelet            Created container dc-timer-timetagger
  Normal   Started         119s (x3 over 2m55s)   kubelet            Started container dc-timer-timetagger
  Warning  BackOff         101s (x14 over 2m54s)  kubelet            Back-off restarting failed container dc-timer-timetagger in pod dc-timer-timetagger-69db5749f4-69kbw_ix-dc-timer(a50b1c27-11b1-433d-944b-c071fa9e3015)
```
</details>

<details>
  <summary>TNS server setup details</summary>

```
OS: TrueNAS-SCALE-23.10.2
hardware specs (short):
Motherboard make and model: GigaByte X570 GAMING X rev 1.0, BIOS: F37a
CPU make and model: AMD Ryzen 9 5950X 16-Core Processor
RAM quantity: 128 GB
SSD for apps: 500 GB Samsung 850 SATA
```
</details>

[EDIT]
Previously I opened a ticket on TrueCharts Discord server in scale-support. They faced the same issue with a fresh installation.
[/EDIT]
