### ISSUE TITLE
Disable Authentication?

### ISSUE THREAD

**Issue by threehappypenguins** [almarklein/timetagger#482]
If I comment out the line in docker-compose.yml
`- TIMETAGGER_CREDENTIALS=test:$$2a$$08$$0CD1NFiIbancwWsu3se1v.RNR/b7YeZd71yg3cZ/3whGlyU6Iny5i  # test:test`

I can successfully spin up the docker container, navigate to the app page, and I don't need to log in. However, if I set up Nginx Proxy Manager so that I access TimeTagger via https, the app page suddenly wants me to sign in... and I can't (obviously) because I haven't set a username and password.

It's a remote server, so I want to use Authelia with 2FA enabled for authentication.

How do I fully disable authentication?

**Comment by almarklein** [comment]
You have, in the sense that the server has no valid credentials. The front-end still presents you with a form though.

If you specify the `proxy_xx` variables in the config ([proxy](https://timetagger.readthedocs.io/en/latest/libapi/)), then the login page should automatically log you in directly.

**Comment by threehappypenguins** [comment]
> You have, in the sense that the server has no valid credentials. The front-end still presents you with a form though.
> 
> If you specify the `proxy_xx` variables in the config ([proxy](https://timetagger.readthedocs.io/en/latest/libapi/)), then the login page should automatically log you in directly.

I still can't get this figured out. Here is what I tried in `docker-compose.yml`:

```
version: "3"
services:
  timetagger:
    image: ghcr.io/almarklein/timetagger
    ports:
      - "80:80"
    volumes:
      - ./_timetagger:/root/_timetagger
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
      - TIMETAGGER_CREDENTIALS=test:$$2a$$08$$0CD1NFiIbancwWsu3se1v.RNR/b7YeZd71yg3cZ/3whGlyU6Iny5i
      - PROXY_AUTH_ENABLED=True
      - PROXY_AUTH_TRUSTED="0.0.0.0/0"
      - PROXY_AUTH_HEADER="test"
```

I am still required to log in with TimeTagger.
